apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-shop-nxt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-shop-nxt
  template:
    metadata:
      labels:
        app: app-shop-nxt
    spec:
      containers:
        - name: app-shop-nxt
          image: jmarcelotse/app-shop-nxt:v2
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: "index.py"  # Define o arquivo principal do Flask
            - name: DB_HOST
              value: "postgres"  # Nome do serviço do banco de dados
            - name: DB_USER
              value: "ecommerce"
            - name: DB_PASSWORD
              value: "Pg1234"
            - name: DB_NAME
              value: "ecommerce"
            - name: DB_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: app-shop-nxt
spec:
  selector:
    app: app-shop-nxt
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort
